// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { WaveContract$Type } from "./WaveContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WaveContract"]: WaveContract$Type;
    ["contracts/WaveContract.sol:WaveContract"]: WaveContract$Type;
  }
}
